import { RISK_PRIORITY, USER_ROLES } from "appConstants";
import { DetailsDate } from "components/custom/detailsDate";
import { DetailsLogs } from "components/custom/detailsLogs";
import { DetailsSelectWithTag } from "components/custom/detailsSelectWithTag";
import { DetailsTextEditor } from "components/custom/detailsTextEditor";
import { DetailsTitle } from "components/custom/detailsTitle";
import { DetailsUsers } from "components/custom/detailsUsers";

import {
  getDefaultColor,
  getRiskPriorityColor,
  getTaskStatusColor,
} from "fe-helpers/utlis";

export const taskDetailsConfig = [
  {
    key: "title",
    dataIndex: "title",
    label: "title",
    tooltip: "edit title",
    parent: "main",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    component: DetailsTitle,
    order: 1,
  },
  {
    key: "finding",
    dataIndex: "finding",
    label: "findings",
    tooltip: "edit findings",
    parent: "main",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    component: DetailsTextEditor,
    order: 2,
  },
  {
    key: "recommendation",
    dataIndex: "recommendation",
    label: "recommendations",
    tooltip: "edit recommendation",
    parent: "main",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    component: DetailsTextEditor,
    order: 4,
  },
  {
    key: "management_response",
    dataIndex: "management_response",
    label: "management response",
    tooltip: "edit response",
    parent: "main",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.HOD],
    component: DetailsTextEditor,
    order: 5,
  },
  {
    key: "action_items",
    dataIndex: "action_items",
    label: "action items",
    tooltip: "edit action items",
    parent: "main",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.HOD],
    component: DetailsTextEditor,
    order: 6,
  },
  {
    key: "risk_rating",
    dataIndex: "risk_rating",
    parent: "sidebar",
    label: "risk rating",
    tooltip: "edit rating",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    options: Object.values(RISK_PRIORITY),
    isMultiple: false,
    getTagColor: getRiskPriorityColor,
    component: DetailsSelectWithTag,
    order: 5,
  },
  {
    key: "owner",
    parent: "sidebar",
    dataIndex: "owner",
    label: "owner",
    tooltip: "edit owner",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.HOD],
    options: [],
    component: DetailsUsers,
    order: 3,
  },
  {
    key: "approved_by",
    parent: "sidebar",
    dataIndex: "approved_by",
    label: "approved by",
    tooltip: "edit owner",
    isEditable: false,
    options: [],
    component: DetailsUsers,
    order: 8,
  },
  {
    key: "department",
    parent: "sidebar",
    dataIndex: "department",
    label: "department",
    tooltip: "edit department",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    options: [],
    isMultiple: false,
    getTagColor: getDefaultColor,
    component: DetailsSelectWithTag,
    order: 4,
  },
  {
    key: "target_date",
    parent: "sidebar",
    dataIndex: "target_date",
    label: "target date",
    tooltip: "edit date",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    component: DetailsDate,
    order: 2,
  },
  {
    key: "status",
    parent: "sidebar",
    dataIndex: "status",
    label: "status",
    tooltip: "edit status",
    isEditable: true,
    canBeEditedBy: Object.values(USER_ROLES),
    options: [],
    isMultiple: false,
    getTagColor: getTaskStatusColor,
    component: DetailsSelectWithTag,
    order: 1,
  },
  {
    key: "date_of_completion",
    parent: "sidebar",
    dataIndex: "date_of_completion",
    label: "date of completion",
    tooltip: "edit date",
    isEditable: false,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    component: DetailsDate,
    order: 9,
  },
  {
    key: "remarks",
    parent: "main",
    addBtnText: "Add Remarks",
    dataIndex: "remarks",
    label: "Remarks",
    isEditable: true,
    canBeEditedBy: Object.values(USER_ROLES),
    component: DetailsLogs,
  },
  {
    key: "logs",
    parent: "main",
    dataIndex: "logs",
    label: "logs",
    isEditable: false,
    canBeEditedBy: [],
    component: DetailsLogs,
  },
  {
    key: "tags",
    parent: "sidebar",
    dataIndex: "tags",
    label: "tags",
    tooltip: "edit tags",
    isEditable: true,
    canBeEditedBy: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
    options: [],
    isMultiple: true,
    getTagColor: getDefaultColor,
    component: DetailsSelectWithTag,
    order: 10,
  },
];
